Add query execution stats for 1.1.0
awslabs/amazon-qldb-driver-dotnet pull request #44
Opened 2021-01-07 01:10 UTC by simonz-bq

- Added query execution stats with unit and integration tests
- Bumped version to 1.1.0
- Updated dependencies

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-01-07 02:00 UTC, alpian commented on Amazon.QLDB.Driver.Tests/ResultTests.cs
> +            Mock<Session> mockSession = new Mock<Session>(null, null, null, null, null);
There seems to be a lot of duplication between tests. Can we clean that up please?

2021-01-07 02:01 UTC, alpian commented on Amazon.QLDB.Driver.Tests/ResultTests.cs
> +            Mock<Session> mockSession = new Mock<Session>(null, null, null, null, null);
Duplicated from above

2021-01-07 02:01 UTC, alpian commented on Amazon.QLDB.Driver/client/IOUsage.cs
> + * Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
2021

2021-01-07 02:06 UTC, alpian requested changes

2021-01-07 02:06 UTC, alpian commented on Amazon.QLDB.Driver/client/TimingInformation.cs
> + * Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
2021

2021-01-07 02:06 UTC, alpian commented on Amazon.QLDB.Driver/result/BufferedResult.cs
> +        private readonly TimingInformation timingInformation;
Are these nullable?

2021-01-07 02:06 UTC, alpian commented on Amazon.QLDB.Driver/result/IResult.cs
> +        IOUsage GetConsumedIOs();
Are these Nullable?

2021-01-07 20:08 UTC, simonz-bq commented on Amazon.QLDB.Driver/result/BufferedResult.cs
> +        private readonly TimingInformation timingInformation;
No, but the contained int64s are.

2021-01-07 20:08 UTC, simonz-bq commented on Amazon.QLDB.Driver/result/IResult.cs
> +        IOUsage GetConsumedIOs();
No, but the contained int64s are.

2021-01-07 20:08 UTC, simonz-bq commented on Amazon.QLDB.Driver/client/TimingInformation.cs
> + * Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
Done

2021-01-07 20:08 UTC, simonz-bq commented on Amazon.QLDB.Driver/client/IOUsage.cs
> + * Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
Done

2021-01-07 20:31 UTC, alpian requested changes
Please address the other comments not added as part of the review (sorry, my bad for not knowing how GH works :))

2021-01-08 22:47 UTC, alpian approved these changes
Nice! :)

2021-01-08 22:49 UTC, merged